### ISSUE TITLE
Navigation Issues with `netbox@4.1.0`

### ISSUE THREAD

**Issue by ndom91** [devon-mar/netbox-kea#109]
First of all, thanks for this great plugin! Besides for a feature request for a simple "All Leases" tab :sweat_smile: I love it!

However, I noticed when using it with `4.1.0-beta1`, that there seem to be some navigation issues. For example, when clicking on the `DHCP v4 Leases` tab, the resulting container remains empty, even though I can see the correct chunk of HTML returned from the server in the network tab of dev tools. I have to reload the page to get it to show up.

Then, in a sort of inverse behaviour, when navigating the individual subnets under the `DHCP v4 Subnets` tab and clicking on one of the subnets, the entire Netbox UI gets replaced with the resulting HTML which should actually just be inserted in the child element of the tab, right?

**Comment by ndom91** [comment]
As I was typign this out and saw myself write the words "HTML Chunk" and "replacement" and such, I realized that I had enabled the new experimental HTMX navigation. 

With that experimental HTMX navigation disabled, these problems disappear :sweat_smile: 

For more details on the HTMX experimental navigation, see: https://github.com/netbox-community/netbox/issues/14736

**Comment by devon-mar** [comment]
I'll probably wait until HTMX navigation is no longer "experimental" before supporting it in this plugin.

I can take a quick look if you're able to send a HAR file.

**Comment by ndom91** [comment]
Looks like I can't upload a `.har` file to GitHub comments here. But the issue just seems to be incorrect and/or missing HTMX [swapping](https://htmx.org/docs/#swapping) attributes.

The network seems to return the correct HTML, for example when clicking on "DHCP v4 Leases", the response contains the HTML for the `<form .. />` containing inputs for searching the subnets and the button to submit. It's just not swapped into place.

In the other case, clicking on a subnet in the list under "DHCP v4 Subnets", the resulting network request contains the HTML for the list of leases in that subnet, but instead of swappign it into the child of the tab component, it swaps it in direclty underneath `<body />`, in effect replacing the rest of Netbox. 

Anyway, since it is still very experimental, no rush :wink: 

You can enable it easily any time in the "Admin" -> "Preferences" tab (`/user/preferences/`) as of version `4.0` or `4.1`, I believe.
