### ISSUE TITLE
Host Reservation Tracking

### ISSUE THREAD

**Issue by bitcollector1** [devon-mar/netbox-kea#18]
Would it be possible to add host reservations into this tool?  The reason I ask is because they are related and if your pool is full of reservations it could be that no IP's are available to be handed out.  

i.e. pool utilization could be 75% but it could be the remaining 25% of the pool is reserved and then there would be no free addresses to hand out. 

Right now I'm looking for a way to square these (2) scenarios up and it would be awesome of this plugin could show if a reservation exists or not.  

```
import requests

s = requests.Session()
s.verify = '/etc/ssl/certs'

headers = {
    'Content-Type': 'application/json',
}


json_data = {
    'command': 'reservation-get-all',
    "arguments": {
        'subnet-id': 5
    },
    'service': [
        'dhcp4',
    ],
}

response = s.post('https://kea.vip.com/', headers=headers, json=json_data, auth=('user', 'pass')) 

for i in response.json()[0]['arguments']['hosts']:
    print(i['ip-address'], i['hw-address']) 

```

**Comment by bitcollector1** [comment]
I could probably write a script to do this audit, but I'm loving your tool so much that I figured it could not hurt to ask :)

**Comment by bitcollector1** [comment]
I'm not even sure how all of this would work, so if it's too much work, I completely understand.

**Comment by bitcollector1** [comment]
I just implemented the IP Ranges today in NetBox so that's what fueled this request.  

<img width="1339" alt="Screenshot 2023-08-22 at 15 12 18" src="https://github.com/devon-mar/netbox-kea/assets/50723251/18a4544f-e9e5-4ccb-8278-ed9e55cb363d">


The host reservations is the last piece I need before I can put this project to bed :)

**Comment by bitcollector1** [comment]
I just saw the follwing: 

Currently this library is only available to ISC customers with a paid support contract. :(

**Comment by devon-mar** [comment]
Even if possible, I think that this would be outside the scope of this plugin. It seems more of a job for some monitoring software or even NetBox's custom scripts.
