### ISSUE TITLE
NetBox 4.0 support

### ISSUE THREAD

**Issue by bitcollector1** [devon-mar/netbox-kea#73]
Hello, 

Do you have any plans to support NetBox 4.0 new plugin ecosystem?  We've been using this plugin for awhile now and it's amazing but it needs an update for 4.0. 

Thanks again for the great tool!

**Comment by devon-mar** [comment]
Glad you find this plugin useful.

Yes, I do plan on updating this plugin for NetBox 4.0, hopefully in the next couple of weeks.

**Comment by LilTrublMakr** [comment]
https://docs.netbox.dev/en/stable/plugins/development/migration-v4/

**Comment by bitcollector1** [comment]
I attempted the hack at it but I only did the extras edit, looking at the link shared above, there are a few other changes that need to also be made.

**Comment by bitcollector1** [comment]
This is great, very much appreciated.  Seems to be working good at first glance.  

Thanks for making NetBox even better! 

Cheers!

**Comment by bitcollector1** [comment]
I'm loving the plugin but I was wondering if you could make the default for the Leases Tab be "Subnet" instead of "IP Address"

<img width="1023" alt="Screenshot 2024-05-23 at 17 13 11" src="https://github.com/devon-mar/netbox-kea/assets/50723251/6d13e082-052b-4620-bb74-b01e20288d37">

It would be awesome if my users could see the entire 10.0.0.0/8 subnet by default 
https://netdevbox.hwe.ebay.com/plugins/kea/servers/1/leases4/?q=10.0.0.0%2F8&by=subnet

<img width="1328" alt="Screenshot 2024-05-23 at 17 14 26" src="https://github.com/devon-mar/netbox-kea/assets/50723251/fe7d9666-bfec-4cb9-983f-67aa065b8c22">

**Comment by bitcollector1** [comment]
An option in the drop down for "ALL LEASES" might also do the trick and be much easier and cleaner in the end.

**Comment by devon-mar** [comment]
>I'm loving the plugin but I was wondering if you could make the default for the Leases Tab be "Subnet" instead of "IP Address"

Could you open a new issue for this?


I'm going to close this issue since it seems that the plugin is working on NetBox 4.0.
