### ISSUE TITLE
All Leases Option 

### ISSUE THREAD

**Issue by bitcollector1** [devon-mar/netbox-kea#80]
I was wondering if it would be possible to add "ALL LEASES" as an option in the drop down menu?  I would like an easy way to show all the leases to the users in one screen and most of them know nothing about subnets. 

Thanks again for the great plugin, It helps provide much needed visibility into our infra and is a huge time saver. 

Cheers!

**Comment by devon-mar** [comment]
What is the use case for this?

I can only see it being practical for deployments with a small number of leases.

**Comment by bitcollector1** [comment]
My end users are not the most network savvy folks. That said, I think I can hack at the plugin to get the desired functionality.

**Comment by devon-mar** [comment]
Instead of hacking the plugin, I think you could accomplish this with a custom link.

Something like:
```
/plugins/kea/servers/{{ object.pk }}/leases6/?q=%3A%3A%2F0&by=subnet
```
as the link URL should work.

**Comment by ndom91** [comment]
For DHCPv4 leases try this "Link URL" `/plugins/kea/servers/{{ object.pk }}/leases4/?q=0.0.0.0%2F0&by=subnet`
